# Generated by Django 3.1.2 on 2020-10-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('User', 'User'), ('Founder', 'Founder'), ('Advisor', 'Advisor'), ('Investor', 'Investor')], default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
