# Generated by Django 3.1.2 on 2020-11-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contry',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('User', 'User'), ('Founder', 'Founder'), ('Advisor', 'Advisor'), ('Investor', 'Investor'), ('Company', 'Company'), ('Event Organizer', 'Event Organizer')], default='User', max_length=20),
        ),
    ]
