# Generated by Django 3.1.2 on 2020-11-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201111_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='contry',
            new_name='country',
        ),
    ]
