# Generated by Django 3.1.2 on 2020-11-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
                ('user_IP', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('user_type', models.CharField(max_length=150)),
                ('log_in_time', models.DateTimeField()),
                ('log_out_time', models.DateTimeField()),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
