# Generated by Django 3.1.2 on 2020-11-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('IP', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Master IP',
                'verbose_name_plural': 'Master IP',
            },
        ),
        migrations.CreateModel(
            name='MyApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
                ('download_link_for_windows', models.CharField(max_length=200)),
                ('download_link_for_linux', models.CharField(max_length=200)),
                ('download_link_for_macos', models.CharField(max_length=200)),
                ('master_IP', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.master_ip')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
            },
        ),
    ]
