# Generated by Django 3.1.2 on 2020-10-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager_id',
            options={'verbose_name': 'Manager ID', 'verbose_name_plural': 'Manager ID'},
        ),
    ]
